{% set name = "pytest-qt" %}
{% set version = "4.0.2" %}
{% set sha256 = "dfc5240dec7eb43b76bcb5f9a87eecae6ef83592af49f3af5f1d5d093acaa93e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - pytest

test:
  requires:
    - pyqt 5.*
    - pytest
  imports:
    - pytestqt
  commands:
    - pytest --help

about:
  home: https://github.com/pytest-dev/pytest-qt
  license: MIT
  license_file: LICENSE
  summary: pytest support for PyQt and PySide applications
  doc_url: http://pytest-qt.readthedocs.io/en/latest/
  dev_url: https://github.com/pytest-dev/pytest-qt

extra:
  recipe-maintainers:
    - nicoddemus
